<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Termsandcondition.aspx.cs" Inherits="Termsandcondition" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 style="text-decoration:underline;font-size:30px;">Terms And Condition</h1>
    <div class="row">
           <p style="font-size:1.5rem;font-style:initial;">We Are Here to Serve You:-</p><p style="font-size: 1.3rem;">The Urbanbanya. Com is a Site where  transaction, information and communication service available to consumers who access urbanbanya.com. Urbanbanya.com  provides an online grocery shopping and delivery service.<br />Urbanbanya.com will deliver grocery orders placed with the urbanbanya Service. Prices of products sold online may differ from those in retail stores. Delivery will be made to the delivery address that you specify when you confirm your order. Prices for products you place in your cart will be guaranteed for the transaction. Payment for groceries and associated shopping and other fees is due at the time of delivery. You are responsible for ensuring that someone is present at the delivery address to receive and pay for deliveries at the specified time of delivery. Anyone at the delivery address who receives the delivery is conclusively presumed to be authorized to receive and pay for the order. </p>
    <br /><br />
    </div>
    <div class="row">
    <p style="font-size: 1.3rem;">Pricing:-</p><p style="font-size: 1.3rem;">Products which are listed on Urbanbanya.com will be sold at MRP unless otherwise specified. The prices mentioned at the time applicable prices at the time of placing an order. Although prices of most of the products do not fluctuate on a daily basis but some of the commodities and fresh food do change on a daily basis which would be updated almost immediately on the portal.</p>
    <br /><p style="font-size: 1.3rem;">Cancellation Policy:-</p><p style="font-size: 1.3rem;">As a customer you can cancel the order anytime before  the cut-off time of the slot for which you have placed an order by calling our customer care number. In such a case we will refund any payments already made by you for the order in form of goodies. If we suspect any fraudulent transaction by any customer or any transaction which defies the terms & conditions of using the website, we at our sole discretion could cancel such orders. We will maintain a negative list of all fraudulent transactions and customers and would deny access to them or cancel any orders placed by them.<br /></p>

     <br /><p style="font-size: 1.3rem;">Returns & Refunds:-</p><p style="font-size: 1.3rem;">We have a "no questions asked return and refund policy" which entitles all our members to return the product at the time of delivery if due to some reason they are not satisfied with the quality or freshness of the product. We will take the returned product back with us and issue a credit note for the value of the return products which will be credited to your Urbanbanya Account . This can be used to pay your subsequent shopping bills.</p>
     </div>
    <div class="row">
        <h2 style="text-decoration:underline;text-align:left;">Product Content:</h2>
        <p style="font-size: 1.3rem;">The images of Products on site are anly to represent it.. We take every effort to maintain same and up to date content related to Product. However, information provided on the Website is sourced from publically available resources and hence we does not claim responsibility or accept liability for any loss or damage due to use based on the same. We do not recommend relying solely on the product information provided. Packaging, product size, product contents & nutritional information may change without any prior intimation.<br />The product nutritional information displayed is based on the following standards or if mentioned so on the product packaging. Use at your own discretion.</p>
        <p style="font-size: 1.3rem;">Property Rights:-<br /></p><p style="font-size: 1.3rem;">(a) Copyright:-</p><p style="font-size: 1.3rem;">Urbabanya.com reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Website.. All rights, including copyright, in this website are owned by Urbanbanya.com. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of Urbanbanya.com. You may not modify, distribute or re-post anything on this website for any purpose. The names and logos and all related product and service names, design marks and slogans are the trademarks or service marks of Urbanbanya.com . All other marks are the property of their respective companies. The materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Website (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Website for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Website or any related software. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Website is strictly prohibited. Urbanbanya.com reserves the right to revoke this authorization at any time, and any use shall be discontinued immediately on written notice from urbanbanya.com.</p>
        <p style="font-size: 1.3rem;">(b) Trademarks :</p><p style="font-size: 1.3rem;"> "urbanbanya," urbanbanya.com,", all urbanbanya.com logos, and all titles, characters, names, graphics and button icons are service marks, trademarks and/or trade dress of urbanbanya.com or otherwise proprietary to urbanbanya.com and may not be used by you for any reason other than as expressly permitted by this Agreement. All other trademarks, service marks, product names and company names or logos appearing on urbanbanya.com are the property of their respective owners.</p>
    </div>
    <div class="row">
        <h2  style="text-decoration:underline;text-align:left;">Your Account:-</h2>
        <p style="font-size: 1.3rem;">All shoppers have to register and login for placing orders on the Site. You have to keep your account and registration details current and correct for communications related to your purchases from the site. By agreeing to the terms and conditions, the shopper agrees to receive promotional communication and newsletters upon registration. The customer can opt out either by unsubscribing in "My Account" or by contacting the customer service. <br />Goodies:-<br />
                  One very purchase of 100/- you will be credited 20 Goodies in your a/c.<br />you can redeem these goodies in our goodies Section</p>
    </div>
    <div class="row">
        <h2  style="text-decoration:underline;text-align:left;">Your Experience:-</h2>
        <p style="font-size: 1.3rem;">
       Customers may write down their suggestions, idea, reviews, comments and other Questions if any or want any  other information in our “ your experience” section but matter should not be  illegal, obscene, threatening, infringing on intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning.  Urbanbanya.com reserves the right to edit or remove such content.</p>
    </div>
    <div class="row">
        <p style="font-size: 1.3rem;">Modification of Terms & Conditions of Service</p>
        <p style="font-size: 1.3rem;">Urban Banya.com may at any time modify the Terms & Conditions of Use of the Website without any prior notification to you. You can access the latest version of these Terms & Conditions at any given time on the Site. You should regularly review the Terms & Conditions on the Site.</p>
          <br />
         <h2  style="text-decoration:underline;text-align:left"> Disclaimer of Warranty and Limitation of Liability :</h2>
        <p style="font-size: 1.3rem;">The use of the Urbanbanya service, urbanbanya.com and the internet is entirely at your own risk. The contents on Urban Banya are  provided on an "as is", "as available" basis. To its full  extent permitted by law urbanbanya.com disclaims all representations and warranties, including, but not limited to, warranties as per  the availability, accuracy or content of information, products or services, and warranties of title, non-infringement, merchantability or fitness for a particular purpose. Urbanbanya Does not Give Warranty that the functions Urbanbanya.com does not warrant that the functions provided by Urbanbanya.com will be uninterrupted or error-free, or that Urbanbanya.com or the server that makes it available are free from viruses or other harmful components. <br />Neither Urbanbanya.com nor any of its directors, employees, agents, licensors or merchants (collectively, its "associates") shall be liable for damages of any kind, including, but not limited to, direct, indirect, incidental, punitive and consequential damages, arising from your use of, or inability to use, the Urbanbanya service, Urbanbanya.com, the internet or for any other claims related in any way to your relationship with Urbanbanya.com.</p>
         <br />
          <h2  style="text-decoration:underline;text-align:left;"> Indemnification:</h2>
        <p style="font-size: 1.3rem;">You agree to indemnify, defend and hold harmless Urbanbanya.com from and against any and all losses, liabilities, claims, damages, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Urbanbanya.com that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by you pursuant to these Terms.</p>
        <h2  style="text-decoration:underline;text-align:left;">Termination:</h2>
        <p style="font-size: 1.3rem;">Urbanbanya.com may suspend or terminate your use of the Website or any Service if it believes, in its sole and absolute discretion that you have breached a term of these Terms.<br />If you or Urbanbanya.com terminates your use of the Website or any Service, Urbanbanya.com may delete any content or other materials relating to your use of the Service and Urbanbanya.com will have no liability to you or any third party for doing so.<br />You shall be liable to pay for any Service or product that you have already ordered till the time of Termination by either party whatsoever. Further, you shall be entitled to your royalty payments as per the User License Agreement that has or is legally deemed accrued to you.</p>
    </div>
    <div class="row">
        <h2  style="text-decoration:underline;text-align:left;"> Privacy and Security :</h2>
        <p style="font-size: 1.3rem;">Your privacy is very important to Urbanbanya.com. </p>
        <p style="font-size: 1.3rem;">(a) Aggregated Information. Urbanbanya.com may use aggregated information regarding its customers and usage of the Urbanbanya Service (such as customer demographics and traffic patterns) and disclose such aggregated information to advertisers, partners and others for various purposes.</p> 
         <p style="font-size: 1.3rem;">(b) Third Party Service Providers. Urbanbanya.com may employ other companies and individuals to perform certain functions such as delivering packages and analyzing data. They may have access to personal information to perform their functions.</p>
        <p style="font-size: 1.3rem;">(c) Sale of Business. Urbanbanya.com may transfer Customer Registration Data and other personal information in connection with the sale of Urbanbanya.com or the sale or transfer of its business operations in your geographic area to a third party provider of grocery ordering or delivery services who agrees to be bound by this Privacy Policy until you consent that such information will be governed by the policies and terms of such third party provider.</p>
        <p style="font-size: 1.3rem;">(d) Enforcement of Agreement or Compliance with Law. Urbanbanya.com may use or disclose personal information when Urbanbanya.com believes it is appropriate to enforce this Agreement, to protect the rights, property or safety of Urbanbanya.com or its users or to comply with the law.</p>
        <br /><br />
        <h2  style="text-decoration:underline;text-align:left;"> Notices :</h2>
        <p style="font-size: 1.3rem;">Urbanbanya.com may give notice to you of a change in this Agreement and any other matter by general posting on Urbanbanya.com.</p>
         <br /><br />
        <h2  style="text-decoration:underline;text-align:left;"> Legal and Miscellaneous :</h2>
        <p style="font-size: 1.3rem;">These Terms of Service constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. The clauses as above shall survive the termination or expiry of this agreement. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
        <p style="font-size: 1.3rem;">(a) Arbitration</p><p style="font-size: 1.3rem;">If any dispute arises between you and Urbanbanya.com during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement and Terms and Conditions the dispute shall be first referred to a sole Arbitrator who shall be an independent and neutral third party identified by Urbanbanya.com. The place of arbitration shall be Jaipur The Arbitration & Conciliation Act, 1996, shall govern the arbitration proceedings. The arbitration proceedings shall be in the Hindi/English language.</p>
         <p style="font-size:21px; font-style:initial;">  (b) Applicable law</p><p style="font-size: 1.3rem;">This site is created and controlled by Urbanbanya.com. The laws of India shall apply and courts in Jaipur shall have jurisdiction in respect of all the terms, conditions and disclaimers. Urbanbanya.com reserves the right to make changes to the website and the terms, conditions and disclaimers at any time and without information to the customers/users of the services/website of Urbanbanya.com. Users are advised to regularly check for any amendments or updates to the terms and conditions contained herein.</p>
   </div>
</asp:Content>

